syntax = "proto3";

package swiftmerge.v01;
import "google/protobuf/empty.proto";
import "google/protobuf/timestamp.proto";

service LSMDB{
  rpc HealthCheck(google.protobuf.Empty) returns (HealthCheckResponse);
  rpc Put(PutRequest) returns (GenericResponse); 
  rpc Delete(DeleteRequest) returns (GenericResponse); 
  rpc BatchWrite(BatchWriteRequest) returns (GenericResponse);
  rpc Get(GetRequest) returns (GetResponse);
  rpc Range(RangeRequest) returns (RangeResponse);
  rpc GracefulShutdown(google.protobuf.Empty) returns (GenericResponse);
  rpc ReloadConfig(ReloadConfigRequest) returns (GenericResponse);
  rpc WriteMetrics(WriteMetricsRequest) returns (WriteMetricsResponse);
  rpc ReadMetrics(ReadMetricsRequest)  returns (ReadMetricsResponse);
};
message HealthCheckResponse{
  google.protobuf.Timestamp time_stamp = 1;
  
}
message PutRequest {
  bytes key = 1;
  bytes value = 2;
  map<string,TypeInfo> metadata = 3;
};
message DeleteRequest{
  bytes key = 1;
}
// put request are executed first followed by delete requests
// (if same key is in both put and delete , delete is ignored)
message BatchWriteRequest{
  repeated PutRequest puts = 1;
  repeated DeleteRequest deletes = 2;
}
message GenericResponse{
}
message GetRequest{
  bytes key = 1;
  FilterParam filter = 2; // optional filter to apply on metadata
}
message FilterParam{
  bool use = 1;
  repeated string metadata_keys = 2; // array of metadata keys to fetch
}
message GetResponse{
  optional bytes value =1;
  map<string,TypeInfo> metadata = 2; 
}
message RangeRequest{
  bytes start_key = 1;
  bytes end_key = 2;
  FilterParam filter = 3; // optional filter to apply on metadata
}
message RangeResponse{
  message KeyValuePair{
    bytes key = 1;
    bytes value = 2;
    map<string,TypeInfo> metadata = 3; 
  }
  repeated KeyValuePair results = 1;
}
message ReloadConfigRequest{
  bytes json_config = 1; // base64 encoded json config
}
message WriteMetricsRequest{
  SuccessfulWritesMetric write_metrics = 1;
  AverageLatency avg_latency = 2;
}
message AverageLatency{
  bool use = 1;
  // if mins == 0  => return all results
  uint64 mins = 2; // keep this strictly defined (1 min , 5 , 10 , 30 , 60)
}
message SuccessfulWritesMetric{
  bool use = 1;
  uint64 memtable = 3;
  // if mins == 0  => return all results
  uint64 mins = 4; // keep this strictly defined (1 min , 5 , 10 , 30 )
}
message WriteMetricsResponse{
  WriteMetrics write_response = 3;   
  AverageLatencyResponse avg_response = 4;
}
message WriteMetrics{
  uint64 total_writes = 1;
  uint64 ss_table_count = 2;
  uint64 ss_table_merged = 3;
}
message AverageLatencyResponse{
  uint64 latency = 1;
}
message ReadMetricsRequest{
  ReadStats total_reads = 1;
  ReadStats total_misses =2;
  AverageLatency avg_latency = 3;
  
}
message ReadStats{
  // ! only a miss if it doesnt exist in memtable + lsm tree
  bool use = 1;
  uint64 memtable_count = 2;
  uint64 lsm_tree_count = 3;
}
message ReadMetricsResponse{
  ReadStatsResponse read_response = 3;   
  AverageLatencyResponse avg_response = 4;
}
message ReadStatsResponse{
  uint64 memtable_reads = 1;
  uint64 lsm_tree_reads = 2;
  uint64 total_misses =3;
}


// utility 
message TypeInfo{
  bytes raw  = 1;
  SupportedMetadataTypes true_type = 2;
}
enum SupportedMetadataTypes{
  SUPPORTED_METADATA_TYPES_UNSPECIFIED = 0 ;
  SUPPORTED_METADATA_TYPES_BOOL = 1;
  SUPPORTED_METADATA_TYPES_RAW_BYTE = 2;
  SUPPORTED_METADATA_TYPES_STRING = 3;
  SUPPORTED_METADATA_TYPES_UINT32 =4;
  SUPPORTED_METADATA_TYPES_UINT64=5;
  SUPPORTED_METADATA_TYPES_INT32 =6;
  SUPPORTED_METADATA_TYPES_INT64=7;
  SUPPORTED_METADATA_TYPES_FLOAT32=8;
  SUPPORTED_METADATA_TYPES_DOUBLE=9;

}